# Generated by Django 5.2.9 on 2026-04-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('Outdoors', 'Outdoors'), ('Indoors', 'Indoors')], default='Outdoors', max_length=10)),
                ('event', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('seconds', 'Seconds'), ('meters', 'Meters')], default='seconds', max_length=10)),
                ('iaaf_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
