# Generated by Django 5.2.9 on 2026-01-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='records',
        ),
    ]
